# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a89e435b5532b7e4c1eb454e823e398d6f79e6d3cb719c16aa4a044b5cb87d8e110e26ebb25c1fc0c57c9c0822596682397c007ad52bd4a00b06722fce9e574

test:
  secret_key_base: dc8b4c70956a4123b53bbc0ab030c50f99e3e9d713486dd3f2422558b2e03986666b07d023aea7983feaad71f1abc99652034c2f69f36423efd7c5a1d423d719

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
